//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThunderDuckEntities : DbContext
    {
        public ThunderDuckEntities()
            : base("name=ThunderDuckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Td_AreaType> Td_AreaType { get; set; }
        public virtual DbSet<Td_Contact> Td_Contact { get; set; }
        public virtual DbSet<Td_Events> Td_Events { get; set; }
        public virtual DbSet<Td_Members> Td_Members { get; set; }
        public virtual DbSet<Td_Slider> Td_Slider { get; set; }
        public virtual DbSet<Td_ThunderDuckType> Td_ThunderDuckType { get; set; }
        public virtual DbSet<Td_Tours> Td_Tours { get; set; }
        public virtual DbSet<Td_Story> Td_Story { get; set; }
        public virtual DbSet<Td_Images> Td_Images { get; set; }
        public virtual DbSet<Td_News> Td_News { get; set; }
    }
}
