//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderDuckGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Td_Images
    {
        public int id { get; set; }
        public string images { get; set; }
        public string images1 { get; set; }
        public string images2 { get; set; }
        public string images3 { get; set; }
        public string images4 { get; set; }
        public string images5 { get; set; }
        public string images6 { get; set; }
        public string images7 { get; set; }
        public string images8 { get; set; }
        public string Title { get; set; }
    }
}
